### ISSUE TITLE
Can I manually control the animation? OR how to refresh button animation status?

### ISSUE THREAD

**Issue by Crepusculo** [SparkYuan/SubmitButton#2]
`startAnimation()` works fine, but `clearAnimation()` is not working.

**Comment by SparkYuan** [comment]
You don't need to invoke startAnimation() manually. All you need to do about the animation is setting the  duration of this animation.

**Comment by pelopidass** [comment]
After pressing the click the animation seems to not refresh to its original status, it's not showing the text. What can I do about this?
